### ISSUE TITLE
No GetVariable,SetVariable,GetVariableList plugin support

### ISSUE THREAD

**Issue by avigi** [x64dbg/blog#9]
There is now possibility to get variables from plugin.
for example if i create variable using Cmd("Avi=1"), there is no option to get this variable.
Script:: has the many option for example-
Script::Argument
Script::Assembler
Script::Label
but non of them gives the option to GetVariable,SetVariable,GetVariableList......

**Comment by mrfearless** [comment]
Please log issues under the main x64dbg repo (https://github.com/x64dbg/x64dbg) and not under the x64dbg blog (unless it is an issue with the blog of course).
